# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_require "dotenv"
KEYSTORE_PATH = nil
FIREBASE_KEY_PATH = nil
BUNDLE_FILE_PATH = nil

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

before_all do
  Dotenv.overload ".env.secret"
  KEYSTORE_PATH = "/Users/saikrishnaramalingam/Desktop/keystore_testci/testci.jks"
  BUNDLE_FILE_PATH = "/Users/saikrishnaramalingam/TestCi/app/debug/app-debug.aab"
 end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

desc "Submit a new Beta Build to Firebase App Distribution"
lane :beta do
    firebase_app_distribution(
      app: "1:619029984188:android:2076b266d84dfdd5e1b1b9",
      android_artifact_type: "AAB",
      android_artifact_path: BUNDLE_FILE_PATH,
      service_credentials_file: FIREBASE_KEY_PATH,
      groups: "group-rendu",
      release_notes: "Lots of amazing new features to test out!"
  )
end

desc "Build debug and test APK for screenshots"
lane :build_for_screengrab do
  gradle(
    task: 'clean'
  )
  gradle(
    task: 'assemble',
    build_type: 'Debug'
  )
  gradle(
    task: 'assemble',
    build_type: 'AndroidTest'
  )
end

end
